# Generated by Django 5.1.4 on 2025-01-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_data',
            name='jpn_ytd',
            field=models.CharField(max_length=255),
        ),
    ]
