# Generated by Django 5.1.4 on 2025-01-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_upload_data_jpn_ytd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_data',
            name='lot_turns',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
