# Generated by Django 5.1.4 on 2025-01-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_upload_data_lot_turns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeform_data',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedform_data',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
