# Generated by Django 5.1.4 on 2025-01-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_activeform_data_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_data',
            name='no_of_samples',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
