# Generated by Django 5.1.4 on 2025-02-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_upload_data_no_of_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_turns_budget', models.FloatField(blank=True, null=True)),
                ('euv3400_budget', models.FloatField(blank=True, null=True)),
                ('exe5000_budget', models.FloatField(blank=True, null=True)),
                ('bu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.bu')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.factory')),
                ('wbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.wbs')),
            ],
        ),
    ]
