# Generated by Django 5.1.4 on 2025-02-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_budgetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotStatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('factory', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hold_code', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('current_operation', models.CharField(blank=True, max_length=255, null=True)),
                ('oper1', models.CharField(blank=True, max_length=255, null=True)),
                ('oper2', models.CharField(blank=True, max_length=255, null=True)),
                ('oper3', models.CharField(blank=True, max_length=255, null=True)),
                ('oper4', models.CharField(blank=True, max_length=255, null=True)),
                ('oper5', models.CharField(blank=True, max_length=255, null=True)),
                ('oper6', models.CharField(blank=True, max_length=255, null=True)),
                ('oper7', models.CharField(blank=True, max_length=255, null=True)),
                ('oper8', models.CharField(blank=True, max_length=255, null=True)),
                ('oper9', models.CharField(blank=True, max_length=255, null=True)),
                ('oper10', models.CharField(blank=True, max_length=255, null=True)),
                ('oper11', models.CharField(blank=True, max_length=255, null=True)),
                ('oper12', models.CharField(blank=True, max_length=255, null=True)),
                ('oper13', models.CharField(blank=True, max_length=255, null=True)),
                ('oper14', models.CharField(blank=True, max_length=255, null=True)),
                ('oper15', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
