# Generated by Django 5.1.4 on 2025-02-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_contractdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_data',
            name='EXE_5000',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
