# Generated by Django 5.1.6 on 2025-03-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_folder_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(max_length=50)),
                ('uploader', models.CharField(max_length=100)),
            ],
        ),
    ]
